import argparse
import json
import sys
from pathlib import Path

from embedding_search import EmbeddingIndex


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(description="Build an embedding index for knowledge records.")
    parser.add_argument("records_json", help="JSON generated by extract_knowledge_md.py")
    parser.add_argument("index_json", help="Output embedding index JSON")
    parser.add_argument(
        "--provider",
        choices=("local-hash", "openai", "compatible"),
        default="local-hash",
        help="Embedding provider. local-hash has no external dependency; openai requires OPENAI_API_KEY.",
    )
    parser.add_argument(
        "--profile",
        default="",
        help="Provider profile from provider_config.py for provider=compatible",
    )
    parser.add_argument(
        "--model",
        default="text-embedding-3-small",
        help="Embedding model name for provider=openai",
    )
    parser.add_argument(
        "--dimensions",
        type=int,
        default=384,
        help="Vector size for provider=local-hash",
    )
    args = parser.parse_args()

    with Path(args.records_json).open("r", encoding="utf-8-sig") as file:
        records = json.load(file)

    index = EmbeddingIndex.from_records(
        records.get("rules", []),
        provider=args.provider,
        model=args.model if args.provider == "openai" else "",
        dimensions=args.dimensions,
        profile=args.profile,
    )
    index.save(args.index_json)
    print(json.dumps({
        "documents": len(index.documents),
        "provider": index.provider,
        "model": index.model,
        "dimensions": index.dimensions,
        "index": args.index_json,
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
