import argparse
import json
import sys
from pathlib import Path

from bm25_search import BM25Index


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(description="Build a BM25 index for knowledge records.")
    parser.add_argument("records_json", help="JSON generated by extract_knowledge_md.py")
    parser.add_argument("index_json", help="Output BM25 index JSON")
    args = parser.parse_args()

    with Path(args.records_json).open("r", encoding="utf-8-sig") as file:
        records = json.load(file)

    index = BM25Index.from_records(records.get("rules", []))
    index.save(args.index_json)
    print(json.dumps({
        "documents": len(index.documents),
        "index": args.index_json,
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
