import argparse
import json
import sys
from pathlib import Path

from faiss_search import build_faiss_index


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(description="Build a FAISS index for knowledge embeddings.")
    parser.add_argument("records_json", help="JSON generated by extract_knowledge_md.py")
    parser.add_argument("index_path", help="Output FAISS index path, usually rules.faiss")
    parser.add_argument("metadata_json", help="Output metadata JSON path")
    parser.add_argument(
        "--provider",
        choices=("local-hash", "openai", "compatible"),
        default="local-hash",
        help="Embedding provider. local-hash has no external dependency; openai requires OPENAI_API_KEY.",
    )
    parser.add_argument(
        "--profile",
        default="",
        help="Provider profile from provider_config.py for provider=compatible",
    )
    parser.add_argument(
        "--model",
        default="text-embedding-3-small",
        help="Embedding model name for provider=openai",
    )
    parser.add_argument(
        "--dimensions",
        type=int,
        default=384,
        help="Vector size for provider=local-hash",
    )
    args = parser.parse_args()

    with Path(args.records_json).open("r", encoding="utf-8-sig") as file:
        records = json.load(file)

    metadata = build_faiss_index(
        records.get("rules", []),
        args.index_path,
        args.metadata_json,
        provider=args.provider,
        model=args.model if args.provider == "openai" else "",
        dimensions=args.dimensions,
        profile=args.profile,
    )
    print(json.dumps({
        "documents": len(metadata.get("documents", [])),
        "provider": metadata.get("provider"),
        "model": metadata.get("model"),
        "dimensions": metadata.get("dimensions"),
        "index": args.index_path,
        "metadata": args.metadata_json,
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
