import argparse
import json
import sys
from pathlib import Path

from bm25_search import BM25Index
from embedding_search import EmbeddingIndex
from faiss_search import build_faiss_index
from index_manifest import write_manifest


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(
        description="Build all retrieval indexes into one directory."
    )
    parser.add_argument("records_json", help="JSON generated by extract_knowledge_md.py")
    parser.add_argument("index_dir", help="Directory for all index files")
    parser.add_argument(
        "--provider",
        choices=("local-hash", "openai", "compatible"),
        default="local-hash",
        help="Embedding provider. local-hash has no external dependency; openai requires OPENAI_API_KEY.",
    )
    parser.add_argument(
        "--profile",
        default="",
        help="Provider profile name from provider_config.py for provider=compatible",
    )
    parser.add_argument(
        "--model",
        default="text-embedding-3-small",
        help="Embedding model name for provider=openai",
    )
    parser.add_argument(
        "--dimensions",
        type=int,
        default=384,
        help="Vector size for provider=local-hash",
    )
    parser.add_argument(
        "--skip-faiss",
        action="store_true",
        help="Do not build FAISS index even when faiss-cpu is installed",
    )
    args = parser.parse_args()

    with Path(args.records_json).open("r", encoding="utf-8-sig") as file:
        records = json.load(file)

    result = build_all_indexes(
        records,
        args.index_dir,
        provider=args.provider,
        model=args.model,
        dimensions=args.dimensions,
        skip_faiss=args.skip_faiss,
        profile=args.profile,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2))


def build_all_indexes(
    records,
    index_dir,
    provider="local-hash",
    model="text-embedding-3-small",
    dimensions=384,
    skip_faiss=False,
    profile="",
):
    index_dir = Path(index_dir)
    index_dir.mkdir(parents=True, exist_ok=True)
    indexes = {}
    rule_records = records.get("rules", [])

    embedding_path = index_dir / "rules_embedding.json"
    embedding_index = EmbeddingIndex.from_records(
        rule_records,
        provider=provider,
        model=model if provider in {"openai", "compatible"} else "",
        dimensions=dimensions,
        profile=profile,
    )
    embedding_index.save(embedding_path)
    indexes["embedding"] = str(embedding_path)

    bm25_path = index_dir / "rules_bm25.json"
    BM25Index.from_records(rule_records).save(bm25_path)
    indexes["bm25"] = str(bm25_path)

    if not skip_faiss:
        faiss_path = index_dir / "rules.faiss"
        faiss_metadata_path = index_dir / "rules_faiss_meta.json"
        try:
            build_faiss_index(
                rule_records,
                faiss_path,
                faiss_metadata_path,
                provider=provider,
                model=model if provider in {"openai", "compatible"} else "",
                dimensions=dimensions,
                precomputed_documents=embedding_index.documents,
                profile=profile,
            )
            indexes["faiss"] = str(faiss_path)
            indexes["faiss_metadata"] = str(faiss_metadata_path)
        except (RuntimeError, ValueError) as error:
            indexes["faiss_error"] = str(error)

    build_config = {
        "provider": provider,
        "model": model if provider in {"openai", "compatible"} else "",
        "dimensions": dimensions,
        "skip_faiss": skip_faiss,
        "profile": profile,
    }
    manifest = write_manifest(index_dir, records, indexes, build_config)
    return {
        "index_dir": str(index_dir),
        "rule_count": len(rule_records),
        "indexes": indexes,
        "manifest": str(index_dir / "index_manifest.json"),
        "records_fingerprint": manifest["records_fingerprint"],
    }


if __name__ == "__main__":
    main()
