import argparse
import json
import sys
from pathlib import Path

from index_manifest import check_freshness


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(
        description="Check whether indexes match the current knowledge records JSON."
    )
    parser.add_argument("records_json", help="Current JSON generated by extract_knowledge_md.py")
    parser.add_argument("index_dir", help="Directory containing index_manifest.json")
    args = parser.parse_args()

    with Path(args.records_json).open("r", encoding="utf-8-sig") as file:
        records = json.load(file)

    result = check_freshness(records, args.index_dir)
    print(json.dumps(result, ensure_ascii=False, indent=2))
    raise SystemExit(0 if result.get("fresh") else 1)


if __name__ == "__main__":
    main()
