import argparse
import json
import sys
from pathlib import Path

from bm25_search import BM25Index
from build_all_indexes import build_all_indexes
from embedding_search import EmbeddingIndex
from faiss_search import FaissRuleIndex
from index_manifest import check_freshness, read_manifest, resolve_index_path
from parse_knowledge_markdown import extract_scene_overview, split_md_records, split_workflow_records
from route_knowledge_query import QueryRouter, load_intent_routes
from skill_memory import SkillMemory


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(
        description="Query extracted Markdown knowledge records."
    )
    parser.add_argument("records_json", help="JSON generated by extract_knowledge_md.py")
    parser.add_argument("query", help="User query")
    parser.add_argument(
        "--docs-dir",
        default=None,
        help="Optional Markdown document directory. When provided, records_json is refreshed before querying.",
    )
    parser.add_argument(
        "--memory-dir",
        default=None,
        help="Directory for alias memory files. Defaults to <skill>/data/memory.",
    )
    parser.add_argument(
        "--intent",
        choices=("topic_list", "workflow", "knowledge_rule", "general_search"),
        default=None,
        help="Optional intent hint from an upstream model",
    )
    parser.add_argument(
        "--intent-routes",
        default=None,
        help="Optional JSON file defining additional intent keywords and actions.",
    )
    parser.add_argument(
        "--bm25-index",
        default=None,
        help="Optional BM25 index JSON generated by build_bm25_index.py",
    )
    parser.add_argument(
        "--embedding-index",
        default=None,
        help="Optional embedding index JSON generated by build_embedding_index.py",
    )
    parser.add_argument(
        "--faiss-index",
        default=None,
        help="Optional FAISS index generated by build_faiss_index.py",
    )
    parser.add_argument(
        "--faiss-metadata",
        default=None,
        help="Metadata JSON generated together with --faiss-index",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=5,
        help="Maximum matches to return for search intent",
    )
    parser.add_argument(
        "--max-rule-chars",
        type=int,
        default=5000,
        help="Maximum characters to show for each matched rule in the formatted answer.",
    )
    parser.add_argument(
        "--retrieval",
        choices=("auto", "semantic", "lexical", "hybrid"),
        default="auto",
        help="Retrieval strategy for search intent. auto chooses from the query.",
    )
    parser.add_argument(
        "--index-dir",
        default=None,
        help="Directory generated by build_all_indexes.py. Overrides individual index paths when present.",
    )
    parser.add_argument(
        "--auto-index",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Automatically build or rebuild indexes in --index-dir when missing or stale.",
    )
    parser.add_argument(
        "--provider",
        choices=("local-hash", "openai", "compatible"),
        default="local-hash",
        help="Embedding provider used when --auto-index builds indexes.",
    )
    parser.add_argument(
        "--profile",
        default="",
        help="Provider profile from provider_config.py when --provider compatible",
    )
    parser.add_argument(
        "--model",
        default="text-embedding-3-small",
        help="Embedding model used when --provider openai builds indexes.",
    )
    parser.add_argument(
        "--dimensions",
        type=int,
        default=384,
        help="Vector size for local-hash indexes built by --auto-index.",
    )
    parser.add_argument(
        "--skip-faiss",
        action="store_true",
        help="Do not build FAISS during --auto-index.",
    )
    args = parser.parse_args()

    records_path = Path(args.records_json)
    if args.docs_dir:
        records = _extract_records(Path(args.docs_dir))
        _save_records(records_path, records)
    else:
        records = _load_records(records_path)

    _ensure_index_dir(args, records)
    memory_dir = _resolve_memory_dir(args.memory_dir)
    skill_memory = SkillMemory(str(memory_dir / "retrieval_skills.json"))

    learned = skill_memory.learn_command(args.query)
    if learned:
        print(json.dumps({"action": "memory", "answer": learned}, ensure_ascii=False, indent=2))
        return

    expanded_query = skill_memory.apply_query_profile(args.query)

    router = QueryRouter(
        records.get("rules", []),
        records.get("workflows", []),
        records.get("scene_overviews", []),
        intent_routes=load_intent_routes(args.intent_routes),
    )
    result = router.route(expanded_query, args.intent)

    if result.get("action") == "search":
        strategy = _select_retrieval_strategy(expanded_query, args.retrieval)
        result["retrieval_strategy"] = strategy
        result["matches"] = _search_by_strategy(
            strategy,
            expanded_query,
            result,
            args,
        )
        result["answer"] = _format_search_answer(result["matches"], args.max_rule_chars)
        answer_style = skill_memory.answer_style()
        if answer_style:
            result["answer_style"] = answer_style
        if getattr(args, "index_freshness", None):
            result["index_freshness"] = args.index_freshness

    result["query"] = expanded_query
    result["memory_policy"] = "记忆仅用于理解提问意图、别名扩展和回答偏好，不作为知识库事实依据。"
    print(json.dumps(result, ensure_ascii=False, indent=2))


def _load_records(path):
    with path.open("r", encoding="utf-8-sig") as file:
        return json.load(file)


def _save_records(path, records):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as file:
        json.dump(records, file, ensure_ascii=False, indent=2)


def _extract_records(docs_dir):
    output = {"rules": [], "workflows": [], "scene_overviews": []}
    for path in sorted(Path(docs_dir).glob("*.md")):
        content = path.read_text(encoding="utf-8-sig")
        output["scene_overviews"].append(extract_scene_overview(content, path.name))
        output["rules"].extend(split_md_records(content, path.name))
        output["workflows"].extend(split_workflow_records(content, path.name))
    return output


def _resolve_memory_dir(memory_dir):
    if memory_dir:
        return Path(memory_dir)
    return Path(__file__).resolve().parents[1] / "data" / "memory"


def _ensure_index_dir(args, records):
    if not args.index_dir:
        return

    freshness = check_freshness(records, args.index_dir, _build_config(args))
    should_build = args.auto_index and not freshness.get("fresh", False)
    if should_build:
        build_result = build_all_indexes(
            records,
            args.index_dir,
            provider=args.provider,
            model=args.model,
            dimensions=args.dimensions,
            skip_faiss=args.skip_faiss,
            profile=args.profile,
        )
        args.index_build = {
            "rebuilt": True,
            "reason": freshness.get("reason", ""),
            "indexes": build_result.get("indexes", {}),
        }
    else:
        args.index_build = {
            "rebuilt": False,
            "reason": freshness.get("reason", ""),
        }

    _apply_index_dir(args, records)


def _apply_index_dir(args, records):
    if not args.index_dir:
        return

    index_dir = Path(args.index_dir)
    manifest = read_manifest(index_dir)
    if manifest:
        indexes = manifest.get("indexes", {})
        args.faiss_index = resolve_index_path(index_dir, indexes.get("faiss")) or args.faiss_index
        args.faiss_metadata = resolve_index_path(index_dir, indexes.get("faiss_metadata")) or args.faiss_metadata
        args.embedding_index = resolve_index_path(index_dir, indexes.get("embedding")) or args.embedding_index
        args.bm25_index = resolve_index_path(index_dir, indexes.get("bm25")) or args.bm25_index
    else:
        args.faiss_index = str(index_dir / "rules.faiss") if (index_dir / "rules.faiss").exists() else args.faiss_index
        args.faiss_metadata = str(index_dir / "rules_faiss_meta.json") if (index_dir / "rules_faiss_meta.json").exists() else args.faiss_metadata
        args.embedding_index = str(index_dir / "rules_embedding.json") if (index_dir / "rules_embedding.json").exists() else args.embedding_index
        args.bm25_index = str(index_dir / "rules_bm25.json") if (index_dir / "rules_bm25.json").exists() else args.bm25_index

    freshness = check_freshness(records, index_dir, _build_config(args))
    args.index_freshness = {
        "fresh": freshness.get("fresh", False),
        "reason": freshness.get("reason", ""),
    }
    if getattr(args, "index_build", None):
        args.index_freshness["auto_build"] = args.index_build


def _build_config(args):
    return {
        "provider": args.provider,
        "model": args.model if args.provider in {"openai", "compatible"} else "",
        "dimensions": args.dimensions,
        "skip_faiss": args.skip_faiss,
        "profile": args.profile,
    }


def _format_search_answer(matches, max_rule_chars=5000):
    if not matches:
        return "知识库中未找到准确依据"

    lines = []
    for index, match in enumerate(matches, start=1):
        meta = match.get("meta", {})
        lines.extend([
            f"{index}. 所属领域：{meta.get('scene', '')}",
            f"   所属主题：{meta.get('branch', '')}",
            f"   所属条目：{meta.get('node', '')}",
            f"   责任主体：{meta.get('actor', '')}",
            f"   检索方式：{match.get('retrieval', '')}",
            f"   匹配分数：{match.get('score', 0)}",
            f"   知识依据：{_compact_rule_text(match.get('text', ''), max_rule_chars)}",
        ])
    return "\n".join(lines)


def _compact_rule_text(text, max_chars=5000):
    _, _, rule = text.partition("知识内容：")
    if not rule:
        _, _, rule = text.partition("规则：")
    compact = " ".join((rule or text).split())
    if max_chars is None or max_chars <= 0:
        return compact
    return compact[:max_chars]


def _select_retrieval_strategy(query, requested):
    if requested != "auto":
        return requested

    lexical_terms = (
        "原文", "包含", "等于", "编号", "代码", "字段", "名称", "条目", "节点",
        "关键字", "关键词", "清单", "列表", "哪条", "第几条",
    )
    semantic_terms = (
        "为什么", "原因", "如何", "怎么", "怎么办", "能否", "是否允许",
        "需要", "要求", "限制", "控制点", "风险", "失败", "异常",
    )

    has_lexical_signal = any(term in query for term in lexical_terms)
    has_semantic_signal = any(term in query for term in semantic_terms)

    if has_lexical_signal and has_semantic_signal:
        return "hybrid"
    if has_lexical_signal:
        return "lexical"
    return "semantic"


def _search_by_strategy(strategy, query, route_result, args):
    if strategy == "semantic":
        return _semantic_search(query, route_result, args)
    if strategy == "lexical":
        return _lexical_search(query, route_result, args)
    if strategy == "hybrid":
        return _merge_matches(
            _semantic_search(query, route_result, args),
            _lexical_search(query, route_result, args),
            args.top_k,
        )
    raise ValueError(f"Unsupported retrieval strategy: {strategy}")


def _semantic_search(query, route_result, args):
    if args.faiss_index and args.faiss_metadata:
        index = FaissRuleIndex(args.faiss_index, args.faiss_metadata)
        matches = index.search(
            query,
            scenes=route_result.get("scenes", []),
            branches=route_result.get("branches", []),
            nodes=route_result.get("nodes", []),
            top_k=args.top_k,
        )
        for match in matches:
            match["retrieval"] = "faiss"
        return matches

    if args.embedding_index:
        index = EmbeddingIndex.load(args.embedding_index)
        matches = index.search(
            query,
            scenes=route_result.get("scenes", []),
            branches=route_result.get("branches", []),
            nodes=route_result.get("nodes", []),
            top_k=args.top_k,
        )
        for match in matches:
            match["retrieval"] = "embedding"
        return matches

    return []


def _lexical_search(query, route_result, args):
    if not args.bm25_index:
        return []
    index = BM25Index.load(args.bm25_index)
    matches = index.search(
        query,
        scenes=route_result.get("scenes", []),
        branches=route_result.get("branches", []),
        nodes=route_result.get("nodes", []),
        top_k=args.top_k,
    )
    for match in matches:
        match["retrieval"] = "bm25"
    return matches


def _merge_matches(primary, secondary, top_k):
    fused = {}
    for source, matches in (("semantic", primary), ("lexical", secondary)):
        for rank, match in enumerate(matches, start=1):
            key = match.get("record_index")
            item = fused.setdefault(key, {"match": dict(match), "score": 0.0, "sources": []})
            item["score"] += 1.0 / (60 + rank)
            item["sources"].append(source)

    ranked = sorted(fused.values(), key=lambda item: item["score"], reverse=True)
    output = []
    for item in ranked[:top_k]:
        match = item["match"]
        match["score"] = round(item["score"], 6)
        match["retrieval"] = "+".join(item["sources"])
        output.append(match)
    return output


if __name__ == "__main__":
    main()
